### PR TITLE
Login session

### PR DESCRIPTION
**Pull request by TaberIV**
Okay @benwaffle go and tear my code apart thanks.

Actually though, very weird thing that I also commented on in my other branch. For some reason a lot of the nice imports from index.js files that I assume @benwaffle wrote just _didn't_ work for me? So that would be nice to fix.

Anyway the code works now and I seem to have fixed all of the bugs. Let me know how wrong I am.

### CODE REVIEW

**Comment by benwaffle** [comment]
I don't like having to deal with cookies and sessions manually. I would start from scratch, create a new branch off of master, add https://github.com/expressjs/session to our server, set `req.session.userId` on login, and create a new route that returns user data if the user is logged (because cookies persist between page loads, and the server can check if req.session.userId). You'd also have to add a logout route that deletes `req.session.userId`

**Comment by TaberIV** [comment]
I already made that logout route. The front end doesn't use express so you'd want to introduce that?

**Comment by TaberIV** [comment]
The effort of dealing with cookies manually has already been done. I don't really see the point of redoing a feature for a project that is due in 2 days.

**Comment by benwaffle** [comment]
express cannot be used on the frontend. i'm saying just add the session middleware

**Pull request closed without merging**
